panels=panel1

[panel1]
plugins=mainmenu,installer,clavier,taskbar,volume,luminosite,batterie,showdesktop
position=Bottom
desktop=0

[mainmenu]
type=mainmenu
filterClear=true

[installer]
type=customcommand
alignment=Left
text=Installer
icon=drive-harddisk
click=qterminal -e /usr/bin/r36os-installer

[clavier]
type=customcommand
alignment=Left
text=ABC
click=/usr/bin/r36os-clavier

[taskbar]
type=taskbar
buttonWidth=120
closeOnMiddleClick=true
groupingEnabled=false

[volume]
device=0
type=volume

[luminosite]
type=customcommand
alignment=Right
command=/usr/bin/r36os-luminosite
text=%1
repeat=true
repeatTimer=5
click=/usr/bin/r36os-luminosite +

[batterie]
type=customcommand
alignment=Right
command=/usr/bin/r36os-batterie
text=%1
repeat=true
repeatTimer=20

[showdesktop]
alignment=Right
type=showdesktop
