Section "Device"
    Identifier "ecran"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "dalle"
EndSection

Section "Screen"
    Identifier "ecran0"
    Device "ecran"
    Monitor "dalle"
    DefaultDepth 24
EndSection

Section "ServerLayout"
    Identifier "bureau"
    Screen "ecran0"
EndSection
